import type { IBookmarkItem } from '@/shared/types/bookmarks';

export const mockData: IBookmarkItem[] = [
  {
    children: [
      {
        children: [
          {
            children: [
              {
                children: [
                  {
                    children: [
                      {
                        dateAdded: Date.now(),
                        id: '13',
                        parentId: '12',
                        title: 'Nested Bookmark Level 3',
                        url: 'https://deep.link.example.com/',
                      },
                    ],
                    dateAdded: Date.now(),
                    id: '12',
                    parentId: '11',
                    title: 'Nested Folder Level 2',
                  },
                ],
                dateAdded: Date.now(),
                id: '11',
                parentId: '10',
                title: 'Nested Folder Level 1',
              },
              {
                children: [],
                dateAdded: Date.now(),
                id: '14',
                parentId: '10',
                title: 'Empty Folder',
              },
              {
                dateAdded: Date.now(),
                id: '14b',
                parentId: '10',
                title: 'Example Link Inside Long Title Folder',
                url: 'https://example.com/inside-long-folder',
              },
            ],
            dateAdded: Date.now(),
            id: '10',
            parentId: '1',
            title: '📚 Long Title Folder with Special Characters !@#$%^&*()',
          },
          {
            children: [
              {
                dateAdded: Date.now(),
                id: '16',
                parentId: '15',
                title: 'GitHub',
                url: 'https://github.com',
              },
              {
                dateAdded: Date.now(),
                id: '17',
                parentId: '15',
                title: 'Stack Overflow',
                url: 'https://stackoverflow.com',
              },
              {
                children: [],
                dateAdded: Date.now(),
                id: '18',
                parentId: '15',
                title: 'Projects',
              },
              {
                dateAdded: Date.now(),
                id: '30',
                parentId: '15',
                title: '',
                url: 'https://empty-title.com',
              },
            ],
            dateAdded: Date.now(),
            id: '15',
            parentId: '1',
            title: 'Mixed Content',
          },
          {
            children: [],
            dateAdded: Date.now(),
            id: '19',
            parentId: '1',
            title: 'Empty Folder at Root Level',
          },
          {
            children: [
              {
                dateAdded: Date.now(),
                id: '33',
                parentId: '32',
                title: 'TypeScript Docs',
                url: 'https://www.typescriptlang.org/docs/',
              },
              {
                dateAdded: Date.now(),
                id: '34',
                parentId: '32',
                title: 'MDN Web Docs',
                url: 'https://developer.mozilla.org/',
              },
              {
                dateAdded: Date.now(),
                id: '35',
                parentId: '32',
                title: 'Mozilla Firefox',
                url: 'https://www.mozilla.org/firefox/',
              },
              {
                dateAdded: Date.now(),
                id: '36',
                parentId: '32',
                title: 'DevDocs',
                url: 'https://devdocs.io',
              },
              {
                dateAdded: Date.now(),
                id: '37',
                parentId: '32',
                title: 'React – Official Site',
                url: 'https://reactjs.org/',
              },
              {
                dateAdded: Date.now(),
                id: '38',
                parentId: '32',
                title: 'Node.js Documentation',
                url: 'https://nodejs.org/en/docs/',
              },
              {
                dateAdded: Date.now(),
                id: '39',
                parentId: '32',
                title: 'JavaScript Info – Deep JS Guide',
                url: 'https://javascript.info',
              },
              {
                dateAdded: Date.now(),
                id: '40',
                parentId: '32',
                title: 'Frontend Masters',
                url: 'https://frontendmasters.com',
              },
              {
                dateAdded: Date.now(),
                id: '51',
                parentId: '32',
                title: 'StackBlitz',
                url: 'https://stackblitz.com/',
              },
              {
                dateAdded: Date.now(),
                id: '52',
                parentId: '32',
                title: 'CodeSandbox',
                url: 'https://codesandbox.io',
              },
              {
                dateAdded: Date.now(),
                id: '53',
                parentId: '32',
                title: 'W3Schools',
                url: 'https://w3schools.com',
              },
            ],
            dateAdded: Date.now(),
            id: '32',
            parentId: '1',
            title: '💾 Development Resources',
          },
        ],
        dateAdded: Date.now(),
        id: '1',
        parentId: '0',
        title: 'Bookmarks Menu',
      },
      {
        children: [
          {
            dateAdded: Date.now(),
            id: '61',
            parentId: '2',
            title: 'Gmail',
            url: 'https://gmail.com',
          },
          {
            dateAdded: Date.now(),
            id: '62',
            parentId: '2',
            title: 'Calendar',
            url: 'https://calendar.google.com',
          },
        ],
        dateAdded: Date.now(),
        id: '2',
        parentId: '0',
        title: 'Bookmarks Toolbar',
      },
      {
        children: [
          {
            dateAdded: Date.now(),
            id: '21', // Duplicate ID
            parentId: '3',
            title: 'Duplicate ID Bookmark',
            url: 'https://duplicate.example.com/',
          },
          {
            children: [
              {
                dateAdded: Date.now(),
                id: '41',
                parentId: '40',
                title: 'JSON Formatter',
                url: 'https://jsonformatter.org',
              },
              {
                dateAdded: Date.now(),
                id: '42',
                parentId: '40',
                title: 'RegExr',
                url: 'https://regexr.com',
              },
              {
                dateAdded: Date.now(),
                id: '43',
                parentId: '40',
                title: 'Lorem Ipsum Generator',
                url: 'https://lipsum.com',
              },
            ],
            dateAdded: Date.now(),
            id: '40',
            parentId: '3',
            title: '⚙️ Tools & Utilities',
          },
          {
            children: [
              {
                dateAdded: Date.now(),
                id: '45',
                parentId: '44',
                title: 'Dribbble',
                url: 'https://dribbble.com',
              },
              {
                dateAdded: Date.now(),
                id: '46',
                parentId: '44',
                title: 'Behance',
                url: 'https://www.behance.net/',
              },
            ],
            dateAdded: Date.now(),
            id: '44',
            parentId: '3',
            title: '🎨 Design Inspiration',
          },
          {
            children: [
              {
                dateAdded: Date.now(),
                id: '48',
                parentId: '47',
                title: 'npm',
                url: 'https://www.npmjs.com',
              },
              {
                dateAdded: Date.now(),
                id: '49',
                parentId: '47',
                title: 'Yarn',
                url: 'https://yarnpkg.com',
              },
              {
                dateAdded: Date.now(),
                id: '50',
                parentId: '47',
                title: 'pnpm',
                url: 'https://pnpm.io',
              },
            ],
            dateAdded: Date.now(),
            id: '47',
            parentId: '3',
            title: '📦 Package Managers',
          },
        ],
        dateAdded: Date.now(),
        id: '3',
        parentId: '0',
        title: 'Other Bookmarks',
      },
      // Loose bookmarks that should go into "Uncategorized"
      {
        dateAdded: Date.now(),
        id: '70',
        parentId: '0',
        title: 'Loose Bookmark 1',
        url: 'https://example1.com',
      },
      {
        dateAdded: Date.now(),
        id: '71',
        parentId: '0',
        title: 'Loose Bookmark 2',
        url: 'https://example2.com',
      },
    ],
    dateAdded: Date.now(),
    id: '0',
    title: '',
  },
];
