import type { IBookmarkItem } from '@/shared/types/bookmarks';

export const mockData: IBookmarkItem[] = [
  {
    id: '0',
    title: '',
    dateAdded: Date.now(),
    children: [
      {
        id: '1',
        title: 'Bookmarks Menu',
        parentId: '0',
        dateAdded: Date.now(),
        children: [
          {
            id: '10',
            title: '📚 Long Title Folder with Special Characters !@#$%^&*()',
            parentId: '1',
            dateAdded: Date.now(),
            children: [
              {
                id: '11',
                title: 'Nested Folder Level 1',
                parentId: '10',
                dateAdded: Date.now(),
                children: [
                  {
                    id: '12',
                    title: 'Nested Folder Level 2',
                    parentId: '11',
                    dateAdded: Date.now(),
                    children: [
                      {
                        id: '13',
                        title: 'Nested Bookmark Level 3',
                        parentId: '12',
                        url: 'https://deep.link.example.com/',
                        dateAdded: Date.now(),
                      },
                    ],
                  },
                ],
              },
              {
                id: '14',
                title: 'Empty Folder',
                parentId: '10',
                dateAdded: Date.now(),
                children: [],
              },
              {
                id: '14b',
                title: 'Example Link Inside Long Title Folder',
                parentId: '10',
                url: 'https://example.com/inside-long-folder',
                dateAdded: Date.now(),
              },
            ],
          },
          {
            id: '15',
            title: 'Mixed Content',
            parentId: '1',
            dateAdded: Date.now(),
            children: [
              {
                id: '16',
                title: 'GitHub',
                parentId: '15',
                url: 'https://github.com',
                dateAdded: Date.now(),
              },
              {
                id: '17',
                title: 'Stack Overflow',
                parentId: '15',
                url: 'https://stackoverflow.com',
                dateAdded: Date.now(),
              },
              {
                id: '18',
                title: 'Projects',
                parentId: '15',
                dateAdded: Date.now(),
                children: [],
              },
              {
                id: '30',
                title: '',
                parentId: '15',
                url: 'https://empty-title.com',
                dateAdded: Date.now(),
              },
            ],
          },
          {
            id: '19',
            title: 'Empty Folder at Root Level',
            parentId: '1',
            dateAdded: Date.now(),
            children: [],
          },
          {
            id: '32',
            title: '💾 Development Resources',
            parentId: '1',
            dateAdded: Date.now(),
            children: [
              {
                id: '33',
                title: 'TypeScript Docs',
                parentId: '32',
                url: 'https://www.typescriptlang.org/docs/',
                dateAdded: Date.now(),
              },
              {
                id: '34',
                title: 'MDN Web Docs',
                parentId: '32',
                url: 'https://developer.mozilla.org/',
                dateAdded: Date.now(),
              },
              {
                id: '35',
                title: 'Mozilla Firefox',
                parentId: '32',
                url: 'https://www.mozilla.org/firefox/',
                dateAdded: Date.now(),
              },
              {
                id: '36',
                title: 'DevDocs',
                parentId: '32',
                url: 'https://devdocs.io',
                dateAdded: Date.now(),
              },
              {
                id: '37',
                title: 'React – Official Site',
                parentId: '32',
                url: 'https://reactjs.org/',
                dateAdded: Date.now(),
              },
              {
                id: '38',
                title: 'Node.js Documentation',
                parentId: '32',
                url: 'https://nodejs.org/en/docs/',
                dateAdded: Date.now(),
              },
              {
                id: '39',
                title: 'JavaScript Info – Deep JS Guide',
                parentId: '32',
                url: 'https://javascript.info',
                dateAdded: Date.now(),
              },
              {
                id: '40',
                title: 'Frontend Masters',
                parentId: '32',
                url: 'https://frontendmasters.com',
                dateAdded: Date.now(),
              },
              {
                id: '51',
                title: 'StackBlitz',
                parentId: '32',
                url: 'https://stackblitz.com/',
                dateAdded: Date.now(),
              },
              {
                id: '52',
                title: 'CodeSandbox',
                parentId: '32',
                url: 'https://codesandbox.io',
                dateAdded: Date.now(),
              },
              {
                id: '53',
                title: 'W3Schools',
                parentId: '32',
                url: 'https://w3schools.com',
                dateAdded: Date.now(),
              },
            ],
          },
        ],
      },
      {
        id: '2',
        title: 'Bookmarks Toolbar',
        parentId: '0',
        dateAdded: Date.now(),
        children: [
          {
            id: '61',
            title: 'Gmail',
            parentId: '2',
            url: 'https://gmail.com',
            dateAdded: Date.now(),
          },
          {
            id: '62',
            title: 'Calendar',
            parentId: '2',
            url: 'https://calendar.google.com',
            dateAdded: Date.now(),
          },
        ],
      },
      {
        id: '3',
        title: 'Other Bookmarks',
        parentId: '0',
        dateAdded: Date.now(),
        children: [
          {
            id: '21', // Duplicate ID
            title: 'Duplicate ID Bookmark',
            parentId: '3',
            url: 'https://duplicate.example.com/',
            dateAdded: Date.now(),
          },
          {
            id: '40',
            title: '⚙️ Tools & Utilities',
            parentId: '3',
            dateAdded: Date.now(),
            children: [
              {
                id: '41',
                title: 'JSON Formatter',
                parentId: '40',
                url: 'https://jsonformatter.org',
                dateAdded: Date.now(),
              },
              {
                id: '42',
                title: 'RegExr',
                parentId: '40',
                url: 'https://regexr.com',
                dateAdded: Date.now(),
              },
              {
                id: '43',
                title: 'Lorem Ipsum Generator',
                parentId: '40',
                url: 'https://lipsum.com',
                dateAdded: Date.now(),
              },
            ],
          },
          {
            id: '44',
            title: '🎨 Design Inspiration',
            parentId: '3',
            dateAdded: Date.now(),
            children: [
              {
                id: '45',
                title: 'Dribbble',
                parentId: '44',
                url: 'https://dribbble.com',
                dateAdded: Date.now(),
              },
              {
                id: '46',
                title: 'Behance',
                parentId: '44',
                url: 'https://www.behance.net/',
                dateAdded: Date.now(),
              },
            ],
          },
          {
            id: '47',
            title: '📦 Package Managers',
            parentId: '3',
            dateAdded: Date.now(),
            children: [
              {
                id: '48',
                title: 'npm',
                parentId: '47',
                url: 'https://www.npmjs.com',
                dateAdded: Date.now(),
              },
              {
                id: '49',
                title: 'Yarn',
                parentId: '47',
                url: 'https://yarnpkg.com',
                dateAdded: Date.now(),
              },
              {
                id: '50',
                title: 'pnpm',
                parentId: '47',
                url: 'https://pnpm.io',
                dateAdded: Date.now(),
              },
            ],
          },
        ],
      },
      // Loose bookmarks that should go into "Uncategorized"
      {
        id: '70',
        title: 'Loose Bookmark 1',
        parentId: '0',
        url: 'https://example1.com',
        dateAdded: Date.now(),
      },
      {
        id: '71',
        title: 'Loose Bookmark 2',
        parentId: '0',
        url: 'https://example2.com',
        dateAdded: Date.now(),
      },
    ],
  },
];
